### ISSUE TITLE
Error executing ng build --prod

### ISSUE THREAD

**Issue by caioverine** [shogogan/racoon-mask#12]
When you execute `ng build --prod` Angular CLI returns this error: `Directive PrimeNgCalendarMaskDirective, Property 'onInput' is private and only accessible within class 'PrimeNgCalendarMaskDirective'`.

I think make property onInput public will solve this issue.

**Comment by kevinnascimento** [comment]
Any news about it?

**Comment by shogogan** [comment]
In which project?

**Comment by kevinnascimento** [comment]
It happens when `PrimeNgCalendarModule` is imported in another project to use the mask in the component `p-calendar`.

**Comment by shogogan** [comment]
can you check if with 1.1.14 it's working please?
