### ISSUE TITLE
The placeholder should be visible onFocus 

### ISSUE THREAD

**Issue by ktriek** [shogogan/racoon-mask#2]
When `[showPlaceholder]="true"` The placeholder should be visible `onFocus `even if the field  is empty.

[Demo](https://stackblitz.com/edit/github-hzr2nn?file=src/app/raw/crude.component.html)
Expected behavior: When the input gets the focus it should show the hint "`__/__/_____`" even if it's empty.

**Comment by shogogan** [comment]
Workibg on it, just noticed a missbehavior and expect to publish a new version day 26-27

**Comment by shogogan** [comment]
Fixed it, there will be improvements on te course of this week :)
