### ISSUE TITLE
Diffrerent separator characters

### ISSUE THREAD

**Issue by mongooseasd** [shogogan/racoon-mask#3]
Hello!

Is there a way to make it work with different date formats, with dash or point as a separator in the date?

Thanks!

**Comment by shogogan** [comment]
Checking it, but it should work with dash or points separators.
just has problems with complex date formats (but there is the customDateFormat that helps with the issue)

**Comment by mongooseasd** [comment]
Ah sorry, i left that out, yes, the primeNg mask part has the problem for us.

If the mask is "DATE": "DD.MM.YYYY HH:mm:ss", it's not working. If the mask is "DATE": "DD-MM-YYYY HH:mm:ss", it's working. 

The regex not escaping the . ?

**Comment by shogogan** [comment]
Primeng dateformat works diferent, try: "dd.mm.yy" with [showTime]='true' and [showSeconds]='true'

https://www.primefaces.org/primeng/#/calendar

**Comment by shogogan** [comment]
tried out the dd.mm.yy and it surelly not works, will need to figure it out :(

**Comment by shogogan** [comment]
Fixed it on racoon-mask-primeng@1.1.7
🎩
