### ISSUE TITLE
Replace instead of pushing the characters on input

### ISSUE THREAD

**Issue by CorporatePittypang** [shogogan/racoon-mask#4]
Hello!

The current version is pushing the character to the next field if you edit the value.
Is there a way to make it as a configurable option, that onEdit it is replacing or pushing the characters?

Thanks!

**Comment by shogogan** [comment]
Will give this a check tonight, it's a pretty nice suggestion 😄
if what i'm thinking works, tomorrow i'll put a new version :)

**Comment by shogogan** [comment]
Added it on 1.1.8 :) 
`[overwriteOnInsert]='true'`
