### ISSUE TITLE
Override on insert primeng problem

### ISSUE THREAD

**Issue by CorporatePittypang** [shogogan/racoon-mask#6]
Hello again :),

![racoon-chrome-primeng-value-shift](https://user-images.githubusercontent.com/10566378/56272640-6fc8d000-60fb-11e9-80cd-9750ed27d6de.gif)
The values are jumping in chrome and IE, onFocus. The same value can't be overriden, i set a PR for that.

Thanks for the help!

**Comment by shogogan** [comment]
Oh, will verify tonight both the PR and this issue (need to publish npm and that sort of things) :)
The thing about the same value can't be overriden i thought it would be good but at the end noticed it was a bad call, just forgot to remove

**Comment by shogogan** [comment]
Fixed on 1.1.9 :)
